### ISSUE TITLE
EPG data out-of-step if channel has no EPG

### ISSUE THREAD

**Issue by dave-p** [PoulKalff/angularJS#4]
![screenshot1](https://user-images.githubusercontent.com/3237636/92363635-b3095180-f0e9-11ea-89e3-29068de1ec2f.png)

The channel 'NOW 70s' has no EPG, however instead of showing a blank line, the EPG for the following channel has been shown. For every following channel the EPG for the previous channel is shown instead, so the programme list for 'ITV2' actually belongs to 'Challenge'.

Presumably a missing NULL check somewhere...

**Comment by PoulKalff** [comment]
Yes, I see the problem..... and you are right of course, I have no check on EPG, I just assume that it is there. Can you show me the API data for the channel......? I don't think that there will be any NULL value o check. since "/api/epg/events/grid" only returns a list of all values for all channels, and there just won't be any for the given channel ID.... would you agree? You know the API much better than I... But if so, I'll just have to do a check on the values returned for each channelID, I guess

**Comment by dave-p** [comment]
```
curl  "http://user:pass@192.168.1.1:9981/api/epg/events/grid?channel=NOW+70s"
{"totalCount":0,"entries":[]}
```
Depending how you're parsing the JSON you could look for zero totalCount perhaps?

**Comment by PoulKalff** [comment]
I made a very quick fix for this, can you check, please?

**Comment by dave-p** [comment]
Yes that works, though if I click on the "No EPG available" box I get a pop-up box with "NaN" where the times would normally be.

**Comment by PoulKalff** [comment]
Ahh ja, it contains no variable, just a dummy epg record, I should probably fill in a dummy-link or something

**Comment by PoulKalff** [comment]
I change the code so the infobox is not shown if no data is available. I'm closing the ticket, thanks again
